--------------------------------------------------------
--  File created - Cumartesi-Aralýk-05-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AKADEMISYENLER
--------------------------------------------------------

  CREATE TABLE "UNIVERLIST"."AKADEMISYENLER" 
   (	"UNÝ_ID" NUMBER(*,0), 
	"BOLUM_ID" NUMBER(*,0), 
	"AKADEMÝSYEN_ISMÝ" VARCHAR2(26 BYTE), 
	"MAKALE_SAYISI" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UNIVERLIST.AKADEMISYENLER
SET DEFINE OFF;
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('1','3','Emrullah Güler','11');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('4','5','Yaþar Uysal','19');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('13','9','DilekS Seçkn','2');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('5','11','Sadi Öztürk','5');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('4','14','Bahri Karaca','7');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('6','7','Remzi Yýldýrým','9');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('9','5','Ýsmail Mazgit','4');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('17','4','Ýlber Ortaylý','0');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('16','9','Celal Þengör','5');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('18','8','Ýstem Köymen','7');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('11','1','Dilek Seçkin','9');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('3','12','Utku Utkulu','6');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('8','15','Sabri Polat','5');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('6','17','Namýk Sarý','7');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('19','13','Baþak Karþýyakalý','1');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('22','6','Üzeyir Coskun','2');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('7','2','Mert Ural','0');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('21','18','Mehmet Yýlmaz','5');
Insert into UNIVERLIST.AKADEMISYENLER ("UNÝ_ID",BOLUM_ID,"AKADEMÝSYEN_ISMÝ",MAKALE_SAYISI) values ('10','20','Aylin Duygulu','8');
--------------------------------------------------------
--  Constraints for Table AKADEMISYENLER
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."AKADEMISYENLER" MODIFY ("UNÝ_ID" NOT NULL ENABLE);
  ALTER TABLE "UNIVERLIST"."AKADEMISYENLER" MODIFY ("BOLUM_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AKADEMISYENLER
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."AKADEMISYENLER" ADD CONSTRAINT "UNI_ID" FOREIGN KEY ("UNÝ_ID")
	  REFERENCES "UNIVERLIST"."DEVLET_UNI_SIRALAMA" ("ÜNÝVERSÝTE_SIRALAMASI") ENABLE;
  ALTER TABLE "UNIVERLIST"."AKADEMISYENLER" ADD CONSTRAINT "BOLUM_ID" FOREIGN KEY ("BOLUM_ID")
	  REFERENCES "UNIVERLIST"."BOLUM_SIRALAMA" ("BÖLÜM_SIRALAMASI") ENABLE;
